import { ConsumptionApiData, ConsumptionData, StatisticsApi, Statistics } from './consumption';
import { DeviceApi, Device } from './device';
import { InstallationApi, Installation } from './installation';
import { NotificationApi } from './notification';
import { SceneApi, Scene } from './scene';
import { OutputApi, Output } from './output';
import { Room, RoomApi } from './room';
import { Sensor, SensorApi } from './sensor';
import { ShutterApi, Shutter } from './shutter';
import { ThermostatApi, Thermostat } from './thermostat';
import { User, UserApi } from './user';
export declare const parseApiResponse: {
    toConsumptionData: (response: ConsumptionApiData) => ConsumptionData;
    toStatistics: (response: StatisticsApi) => Statistics;
    toDevice: (response: DeviceApi) => Device;
    toInstallation: (response: InstallationApi) => Installation;
    toNotification: (response: NotificationApi) => Notification;
    toOutput: (response: OutputApi) => Output;
    toRoom: (response: RoomApi) => Room;
    toScene: (response: SceneApi) => Scene;
    toSensor: (response: SensorApi) => Sensor;
    toShutter: (response: ShutterApi) => Shutter;
    toThermostat: (response: ThermostatApi) => Thermostat;
    toUser: (response: UserApi) => User;
};
